package com.work.itpa.rules;

import java.util.List;
import com.work.itpa.rules.FiConstants;

import function com.work.itpa.rules.FiUtil.isAvailable;

/**
Messages are global objects 

**/

global java.util.List messages

rule "Get List of all deductions which can be availed for 80"   
    when
        $deduction : Deduction ()
        $result : FinPersonResult( )
    then
    	$result.addDeduction($deduction);
end
