package com.work.itpa.rules;

import com.work.itpa.domain.SummaryDeduction;


rule "Initiate Summary Deductions"
	when
		not (SummaryDeduction())
	then
		System.out.println("Summary Objects initiated....");
				
		SummaryDeduction qqb = new SummaryDeduction("80QQB");
		qqb.setMaxAmount(new BigDecimal("300000"));
		insert(qqb);
		
		SummaryDeduction rrb = new SummaryDeduction("80RRB");
		rrb.setMaxAmount(new BigDecimal("300000"));
		insert(rrb);
		
		SummaryDeduction tta = new SummaryDeduction("80TTA");
		tta.setMaxAmount(new BigDecimal("10000"));
		insert(tta);	
		
		SummaryDeduction ccd1b = new SummaryDeduction("80CCD1B");
		ccd1b.setMaxAmount(new BigDecimal("50000"));
		insert(ccd1b);		
		
		SummaryDeduction gga = new SummaryDeduction("80GGA");
		insert(gga);		
		
		SummaryDeduction ggc = new SummaryDeduction("80GGC");
		insert(ggc);		
		
		SummaryDeduction g = new SummaryDeduction("80G");
		insert(g);	
		
		SummaryDeduction gg = new SummaryDeduction("80GG");
		insert(gg);				
		
		SummaryDeduction atc = new SummaryDeduction("80C");
		atc.setMaxAmount(new BigDecimal("150000"));
		insert(atc);
		
		SummaryDeduction ate = new SummaryDeduction("80E");
		insert(ate);			
				
		SummaryDeduction atd = new SummaryDeduction("80D");
		insert(atd);
		
end

/**
	Retrieve all summary deductions from working memory
**/

query "Get Summary Deductions"
	$sd : SummaryDeduction()
end


