package com.work.itpa.rules;

import com.work.itpa.domain.SummaryDeduction;
import com.work.itpa.domain.ItpaConfig;


rule "Initiate Summary Deductions"
	when
		not (SummaryDeduction())
		$config: ItpaConfig()
	then		
	
		
		SummaryDeduction atc = new SummaryDeduction("80C");
		atc.setMaxAmount($config.getBigDecimal("atc.maxAmount"));
		insert(atc);
		
		SummaryDeduction atccc = new SummaryDeduction("80CCC");
		atccc.setMaxAmount($config.getBigDecimal("atccc.maxAmount"));
		insert(atccc);
	
	
	
		SummaryDeduction qqb = new SummaryDeduction("80QQB");
		qqb.setMaxAmount($config.getBigDecimal("atqqb.maxAmount"));
		insert(qqb);
		
		SummaryDeduction rrb = new SummaryDeduction("80RRB");
		rrb.setMaxAmount($config.getBigDecimal("atrrb.maxAmount"));
		insert(rrb);
		
		SummaryDeduction tta = new SummaryDeduction("80TTA");
		tta.setMaxAmount($config.getBigDecimal("attta.maxAmount"));
		insert(tta);
		
		SummaryDeduction ccd1 = new SummaryDeduction("80CCD1");
		insert(ccd1);				
		
		SummaryDeduction ccd1b = new SummaryDeduction("80CCD1B");
		ccd1b.setMaxAmount($config.getBigDecimal("atccd1b.maxAmount"));
		insert(ccd1b);		
		
		SummaryDeduction gga = new SummaryDeduction("80GGA");
		insert(gga);		
		
		SummaryDeduction ggc = new SummaryDeduction("80GGC");
		insert(ggc);		
		
		SummaryDeduction g = new SummaryDeduction("80G");
		insert(g);	
		
		SummaryDeduction gg = new SummaryDeduction("80GG");
		insert(gg);				
		SummaryDeduction ate = new SummaryDeduction("80E");
		insert(ate);			
				
		SummaryDeduction atd = new SummaryDeduction("80D");
		insert(atd);
		
		SummaryDeduction atu = new SummaryDeduction("80U");
		insert(atu);		
		
		SummaryDeduction atdd = new SummaryDeduction("80DD");
		insert(atdd);	
		
		SummaryDeduction atddb = new SummaryDeduction("80DDB");
		insert(atddb);
		
end

/**
	Retrieve all summary deductions from working memory
**/

query "Get Summary Deductions"
	$summaryDeduction : SummaryDeduction()
end


query "Get All Deductions"
	$deduction : Deduction()
end


