package com.work.itpa.rules;

import java.util.List;
import com.work.itpa.domain.FiConstants;

import function com.work.itpa.utils.FiUtil.isLessThanEqualToMax;
import com.work.itpa.domain.Deduction;
import com.work.itpa.domain.SummaryDeduction;

global java.util.List messages


// 80C related Summary Deduction

rule "Summarize 80C Specific donations - add donations "   
    when
        $summary : SummaryDeduction( sectionType == "80C")
 		$deduction : Deduction ( sectionType == "80C" )        
    then
    	$summary.addDeduction($deduction);
end


// This is not the right way to implement logic as it is hidden inside Java class and not in rules
// Find way to extrat it out.


rule "80C Decide max limit"   
salience -100
    when
    	$summary : SummaryDeduction( sectionType == "80C"  )
    then
    	$summary.setEligibleAmountForMaxLimit();    	
end
