package com.work.itpa.rules;

import java.util.List;
import com.work.itpa.domain.FiConstants;

import function com.work.itpa.utils.FiUtil.isLessThanEqualToMax;
import com.work.itpa.domain.Deduction;
import com.work.itpa.domain.SummaryDeduction;

global java.util.List messages

rule "Summarize 80TTA Specific deductions - add deductions "   
    when
        $summary : SummaryDeduction( sectionType == "80TTA")
 		$deduction : Deduction ( sectionType == "80TTA" )        
    then
    	$summary.addDeduction($deduction);
end


rule "Summarize 80TTA Specific deductions - add eligible amount true"   
    when
        $summary : SummaryDeduction( sectionType == "80TTA")
 		$deduction : Deduction ( sectionType == "80TTA" ,
 								 isLessThanEqualToMax($deduction,$summary) == true )        
    then
    	$summary.addToEligibleAmount($deduction.eligibleDeduction);
    	System.out.println("Added eligible amount to the summary " + $deduction.eligibleDeduction);
end

rule "Summarize 80TTA Specific deductions - add eligible amount false"   
    when
        $summary : SummaryDeduction( sectionType == "80TTA")
 		$deduction : Deduction ( sectionType == "80TTA" ,
 								 isLessThanEqualToMax($deduction,$summary) == false )        
    then
    	$summary.setEligibleAmountToMaxAmount();
    	System.out.println("Setting it to Max");
end
