package com.work.itpa.rules;

import java.util.List;
import com.work.itpa.domain.FiConstants;

import function com.work.itpa.utils.FiUtil.isLessThanEqualToMax;
import com.work.itpa.domain.Deduction;
import com.work.itpa.domain.SummaryDeduction;

global java.util.List messages


// 80GG Specific deductionss

rule "Summarize 80GG Specific donations - add donations "   
    when
        $summary : SummaryDeduction( sectionType == "80GG")
 		$deduction : Deduction ( sectionType == "80GG" )        
    then
    	$summary.addDeduction($deduction);
end


// TODO Handle scenarios if we have multiple deductions and there is no max deduction for summary defined.

rule "80GG - Calculate Max for this deduction ..."   
salience -100
    when
    	$summary : SummaryDeduction( sectionType == "80GG"  )
    then
    	$summary.setMaxFromDeductions();    	
end