package com.work.itpa.rules;

import java.util.List;
import com.work.itpa.domain.FiConstants;

import function com.work.itpa.utils.FiUtil.isLessThanEqualToMax;
import com.work.itpa.domain.Deduction;
import com.work.itpa.domain.SummaryDeduction;

global java.util.List messages


// QQB and RRB are combined into one.

rule "Summarize 80C Specific donations - add donations "   
    when
        $summary : SummaryDeduction( sectionType == "80C")
 		$deduction : Deduction ( sectionType == "80C" )        
    then
    	$summary.addDeduction($deduction);
end

