package com.work.itpa.rules;

import java.util.List;
import com.work.itpa.domain.FiConstants;

import function com.work.itpa.utils.FiUtil.isLessThanEqualToMax;
import com.work.itpa.domain.Deduction;
import com.work.itpa.domain.SummaryDeduction;

global java.util.List messages

rule "Summarize 80TTA Specific deductions - add deductions "   
    when
        $summary : SummaryDeduction( sectionType == "80TTA")
 		$deduction : Deduction ( sectionType == "80TTA" )        
    then
    	$summary.addDeduction($deduction);
end


rule "80TTA - Calculate Max for this deduction ..."   
salience -100
    when
    	$summary : SummaryDeduction( sectionType == "80TTA"  )
    then
    	$summary.setEligibleAmountForMaxLimit();    	
end

