package com.work.itpa.rules;

import java.util.List;
import com.work.itpa.domain.FiConstants;

import function com.work.itpa.utils.FiUtil.isLessThanEqualToMax;
import com.work.itpa.domain.Deduction;
import com.work.itpa.domain.SummaryDeduction;

global java.util.List messages


// 80G Specific deductionss

rule "Summarize 80G Specific donations - add donations "   
    when
        $summary : SummaryDeduction( sectionType == "80G")
 		$deduction : Deduction ( sectionType == "80G" )        
    then
    	$summary.addDeduction($deduction);
end



rule "80G - Calculate Max for this deduction ..."   
salience -100
    when
    	$summary : SummaryDeduction( sectionType == "80G"  )
    then
    	$summary.setMaxFromDeductions();    	
end