version: '2'
services:
    itpadoc-app:
        image: itpadoc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://itpadoc-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=itpadoc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    itpadoc-mongodb:
        extends:
            file: mongodb.yml
            service: itpadoc-mongodb
