version: '2'
services:
    itpa-app:
        image: itpa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://itpa-mysql:3306/itpa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    itpa-mysql:
        extends:
            file: mysql.yml
            service: itpa-mysql
